### ISSUE TITLE
Create Content_Model Abstraction, with method stubs

### ISSUE THREAD

**Issue by alexstandiford** [adiungo/core#20]
Create the `Adiungo\Core\Abstracts\Model` class, as well as empty method stubs.

<details>
<summary>Model in chart</summary>

![Image](https://user-images.githubusercontent.com/8210827/201534099-079c67d8-c4d4-4c61-9b80-02df748b9321.png)

</details>

## Acceptance Criteria

1. The `Content_Model` class exists in the `Adiungo\Core\Abstracts` namespace
2. The `Content_Model` class implements `Underpin\Interfaces\Model`, as well as `Underpin\Interfaces\Identifiable`
3. All methods are created, but not actually implemented (stubbed).
4. The `Content_Model_Test` class exists in the `Adiungo\Core\Tests\Abstracts` namespace
5. The `Content_Model_Test` class extends  `Adiungo\Core\Tests\Abstracts\Unit\Test_Case`
6. Test methods for each method in `Model` are added to `Content_Model_Test`, and are marked [as incomplete](https://phpunit.readthedocs.io/en/9.5/incomplete-and-skipped-tests.html#incomplete-and-skipped-tests-incomplete-tests-examples-sampletest-php).

**Comment by MCFaddis1969** [comment]
<?php
  // abstract class
    abstract class Adiungo\Core\Abstracts\Model {
      // abstract functions
         abstract public function Underpin\Interfaces\Model\Model();
         abstract public function Underpin\Interfaces\Identifiable_Int\Model();
?>

Still working on if my script is correct.  I am refreshing my PHP knowledge on Codecademy atm
